<?php
ob_start();
$pageTitle = 'LIST OF INCOMING PUPILS';
?>
<div class="row">
    <div class="card col-lg-12">
        <div class="card-header">
            <button class="btn btn-block btn-outline-success" data-toggle="modal" data-target="#enrollModal">Enroll</button>
        </div>
    </div>

<!-- Modal for Enroll -->
<div class="modal fade" id="enrollModal" tabindex="-1" aria-labelledby="enrollModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="enrollModalLabel">Select Students to Enroll</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
<form method="POST" action="myclass-list/enroll">
    <div class="modal-body">
        <!-- Search Input -->
        <div class="form-group">
            <input type="text" id="searchInput" class="form-control" placeholder="Search by Name, Id, Gender">
        </div>

        <!-- Student Table -->
        <table class="table table-bordered" id="studentTable">
            <thead>
                <tr>
                    <th>Select</th>
                    <th>Student ID</th>
                    <th>Name</th>
                    <th>Gender</th>
                </tr>
            </thead>
            <tbody id="studentBody">
                <?php foreach ($unenrolledStudents as $student): ?>
                    <tr class="student-row">
                        <td>
                            <input type="checkbox" name="students[]" value="<?= $student['user_id'] ?>">
                        </td>
                        <td><?= htmlspecialchars($student['lrn']. '-' . $student['user_id']) ?></td>
                        <td><?= htmlspecialchars($student['fullname']) ?></td>
                        <td><?= htmlspecialchars($student['gender'] === 'F' ? "Female" : "Male" ) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <!-- No Results Message -->
        <div id="noResultsMessage" class="alert alert-warning" style="display: none;">
            No results found.
        </div>

        <!-- Pagination Controls -->
        <div id="paginationControls" class="d-flex justify-content-center">
            <!-- Pagination links will be generated by JavaScript -->
        </div>

        <!-- Hidden Section ID -->
        <input type="hidden" name="section_id" value="<?= $sectionId ?>">

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="submitEnrollBtn">Enroll Selected</button>
    </div>
</form>

        </div>
    </div>
</div>


</div>

<div class="row">
    <!-- Search Bar Section -->
    <section class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Search Students</h3>
            </div>
            <div class="card-body">
                <input type="text" id="searchBar" class="form-control" placeholder="Search by LRN, First Name, or Last Name" onkeyup="searchStudents()">
            </div>
        </div>
    </section>
</div>

<div class="row">
    <!-- Male Students Section -->
    <section class="col-lg-6 connectedSortable">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">MALE</h3>
            </div>
            <div class="card-body">
                <!-- Male students list -->
                <table class="table table-bordered" id="maleStudentsTable">
                    <thead>
                        <tr>
                            <th>LRN</th>
                            <th>Full Name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($advisoryClass as $student) {
                            if ($student['sex'] == 'M') { ?>
                                <tr class="student-row">
                                    <td class="lrn"><?php echo $student['lrn']; ?></td>
                                    <td class="first-name"><?php echo $student['fullname']; ?></td>
                                    <td>
                                        <!-- Drop and Transfer buttons -->
                                   





  <form action="myclass-list/drop" method="POST" style="display:inline;">
                            <input type="hidden" name="student_id" value="<?php echo $student['profile_id']; ?>">
                            <button type="submit"class="btn btn-danger btn-sm">Drop</button> <!-- Apply btn-sm here -->
                          </form>

                                          

                                        <button class="btn btn-warning btn-sm" onclick="transferTeacher(<?php echo $student['profile_id']; ?>)">Transfer Teacher</button>
                                    </td>
                                </tr>
                            <?php } 
                        } ?>
                    </tbody>
                </table>
                <div id="malePagination" class="pagination-container"></div>
            </div>
        </div>
    </section>

    <!-- Female Students Section -->
    <section class="col-lg-6 connectedSortable">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">FEMALE</h3>
            </div>
            <div class="card-body">
                <!-- Female students list -->
                <table class="table table-bordered" id="femaleStudentsTable">
                    <thead>
                        <tr>
                            <th>LRN</th>
                            <th>Full Name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($advisoryClass as $student) {
                            if ($student['sex'] == 'F') { ?>
                                <tr class="student-row">
                                    <td class="lrn"><?php echo $student['lrn']; ?></td>
                                    <td class="first-name"><?php echo $student['fullname']; ?></td>
                                    <td>
                                        <!-- Drop and Transfer buttons -->
                                        <button class="btn btn-danger btn-sm" onclick="dropStudent(<?php echo $student['profile_id']; ?>)">Drop</button>
                                        <button class="btn btn-warning btn-sm" onclick="transferTeacher(<?php echo $student['profile_id']; ?>)">Transfer Teacher</button>
                                    </td>
                                </tr>
                            <?php } 
                        } ?>
                    </tbody>
                </table>
                <div id="femalePagination" class="pagination-container"></div>
            </div>
        </div>
    </section>
</div>


<script>
    // Function to search students by LRN, First Name, or Last Name
    function searchStudents() {
        let input = document.getElementById('searchBar').value.toLowerCase();
        let maleTableRows = document.querySelectorAll('#maleStudentsTable .student-row');
        let femaleTableRows = document.querySelectorAll('#femaleStudentsTable .student-row');

        // Filter male students
        maleTableRows.forEach(row => {
            let lrn = row.querySelector('.lrn').textContent.toLowerCase();
            let firstName = row.querySelector('.first-name').textContent.toLowerCase();
            let lastName = row.querySelector('.last-name') ? row.querySelector('.last-name').textContent.toLowerCase() : '';

            if (lrn.includes(input) || firstName.includes(input) || lastName.includes(input)) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });

        // Filter female students
        femaleTableRows.forEach(row => {
            let lrn = row.querySelector('.lrn').textContent.toLowerCase();
            let firstName = row.querySelector('.first-name').textContent.toLowerCase();
            let lastName = row.querySelector('.last-name') ? row.querySelector('.last-name').textContent.toLowerCase() : '';

            if (lrn.includes(input) || firstName.includes(input) || lastName.includes(input)) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
    }

    // Function to handle the Drop action
    function dropStudent(profileId) {
        if (confirm('Are you sure you want to drop this student?')) {
            // Send request to drop the student (you can use AJAX for this)
            alert('Dropping student with profile ID: ' + profileId);
            // Implement AJAX to drop the student
        }
    }

    // Function to handle the Transfer Teacher action
    function transferTeacher(profileId) {
        if (confirm('Are you sure you want to transfer this student to another teacher?')) {
            // Send request to transfer the student (you can use AJAX for this)
            alert('Transferring student with profile ID: ' + profileId);
            // Implement AJAX to transfer the student
        }
    }
</script>


<script type="text/javascript">
  function paginateTable(tableId, paginationId, rowsPerPage = 5) {
    const table = document.getElementById(tableId);
    const rows = table.querySelectorAll("tbody tr");
    const paginationContainer = document.getElementById(paginationId);

    // Hide all rows initially
    rows.forEach((row, index) => {
        row.style.display = index < rowsPerPage ? "" : "none";
    });

    // Calculate total pages
    const totalPages = Math.ceil(rows.length / rowsPerPage);

    // Clear existing pagination
    paginationContainer.innerHTML = "";

    // Create pagination buttons
    for (let i = 1; i <= totalPages; i++) {
        const button = document.createElement("button");
        button.textContent = i;
        button.classList.add("btn", "btn-primary", "btn-sm", "mx-1");
        button.addEventListener("click", () => {
            // Show rows for the selected page
            rows.forEach((row, index) => {
                row.style.display =
                    index >= (i - 1) * rowsPerPage && index < i * rowsPerPage
                        ? ""
                        : "none";
            });
        });
        paginationContainer.appendChild(button);
    }
}

// Apply pagination for both tables
document.addEventListener("DOMContentLoaded", () => {
    paginateTable("maleStudentsTable", "malePagination");
    paginateTable("femaleStudentsTable", "femalePagination");
});

</script>




<script type="text/javascript">
  // Validate form before submitting
document.getElementById('submitEnrollBtn').addEventListener('click', function(event) {
    var selectedStudents = document.querySelectorAll('input[name="students[]"]:checked');
    var sectionId = document.querySelector('input[name="section_id"]').value;

    if (selectedStudents.length === 0) {
        event.preventDefault();  // Prevent form submission
        alert('Please select at least one student.');
    } else if (!sectionId) {
        event.preventDefault();  // Prevent form submission
        alert('Invalid section. Please try again.');
    }
});

</script>




<script>
    // Number of items per page
    const itemsPerPage = 10;

    // Function to display students per page and handle search functionality
function displayStudents() {
    var searchTerm = document.getElementById('searchInput').value.toLowerCase();
    var rows = document.querySelectorAll('#studentTable tbody tr');
    var filteredRows = [];
    var totalRows = 0;

    // Filter rows based on search term
    rows.forEach(function(row) {
        var studentId = row.cells[1].textContent.toLowerCase();
        var fullName = row.cells[2].textContent.toLowerCase();
        var gender = row.cells[3].textContent.toLowerCase();

        // Include gender in the filter condition
        if (studentId.includes(searchTerm) || fullName.includes(searchTerm) || gender.includes(searchTerm)) {
            row.style.display = ''; // Show row
            filteredRows.push(row);
        } else {
            row.style.display = 'none'; // Hide row
        }
        if (row.style.display !== 'none') totalRows++;
    });

    // Show "No results" message if no rows match the search
    if (filteredRows.length === 0) {
        document.getElementById('noResultsMessage').style.display = 'block';
    } else {
        document.getElementById('noResultsMessage').style.display = 'none';
    }

    // Pagination
    paginate(filteredRows, totalRows);
}


    // Function to paginate the rows
    function paginate(filteredRows, totalRows) {
        var pageCount = Math.ceil(totalRows / itemsPerPage);
        var paginationControls = document.getElementById('paginationControls');
        paginationControls.innerHTML = ''; // Clear previous pagination links

        // Create pagination links
        for (var i = 1; i <= pageCount; i++) {
            var link = document.createElement('a');
            link.href = '#';
            link.classList.add('page-link');
            link.innerHTML = i;
            link.addEventListener('click', function(e) {
                e.preventDefault();
                showPage(parseInt(this.innerHTML), filteredRows);
            });
            var listItem = document.createElement('li');
            listItem.classList.add('page-item');
            listItem.appendChild(link);
            paginationControls.appendChild(listItem);
        }

        // Show the first page by default
        showPage(1, filteredRows);
    }

    // Function to show specific page of students
    function showPage(page, filteredRows) {
        var startIndex = (page - 1) * itemsPerPage;
        var endIndex = startIndex + itemsPerPage;

        // Hide all rows
        filteredRows.forEach(function(row, index) {
            row.style.display = (index >= startIndex && index < endIndex) ? '' : 'none';
        });
    }

    // Event listener for search input
    document.getElementById('searchInput').addEventListener('input', displayStudents);

    // Initial call to display students and pagination
    displayStudents();
</script>


<?php
$content = ob_get_clean();
include 'views/master.php';
?>
